In [2]:
import numpy as np

In [3]:
array_a = np.array([1,2,3,4,5])

In [4]:
print(array_a)

[1 2 3 4 5]


In [5]:
print(array_a.shape)

(5,)


In [9]:
array_b = np.array([[1,2,3,4,5,],[1,2,3,4,5],[1,2,3,4,5]])

In [10]:
print(array_b)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [11]:
print(array_b.shape)

(3, 5)


In [12]:
import numpy as np

In [17]:
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]

In [18]:
array_abc = np.array([seq_a, seq_b, seq_c])
print(array_abc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(array_abc.shape)

(3, 3)


In [20]:
array_d = np.array([[1,2,3],[4,5,6]])
print(array_d.shape)

(2, 3)
